language: elixir
elixir:
  - 1.9.4
  - 1.10.3
otp_release:
  - 23.0
  - 22.2
  - 21.3
notifications:
  email:
    - vince@newrelic.com
services:
  - docker
script:
  - mix format --check-formatted
  - mix test
  - cd examples
  - docker-compose up -d
  - mix deps.get
  - mix format --check-formatted
  - mix test
  - mix instrumented_task.example_task
